### ISSUE TITLE
Android issues on CM4 and Pi 400 

### ISSUE THREAD

**Issue by cspensky** [RPi-Distro/bluez-firmware#10]
Certain Android devices (e.g., Pixel 6, 7, Galaxy S10, S21 Ultra, S22) struggle to connect to the Raspberry Pi over BLE, simply reporting a `Timeout`

The detailed issues of this bug can be found here: https://github.com/RPi-Distro/bluez-firmware/issues/9

This issue is to track the Synaptics 43456 firmware update seperately

**Comment by pelwell** [comment]
There is now a ticket open with Synaptics as well. I hope Infineon's experiences can speed things up for them.

**Comment by pelwell** [comment]
Synaptics have said that your issue sounds familiar, and are seeking confirmation of which version we are shipping now (given). It sounds like a trial version may not be far off.

**Comment by cspensky** [comment]
Thanks a million for pushing this!  This has been causing us a lot of headaches internally.

**Comment by pelwell** [comment]
I have an image to test. The naming makes it look like it could be a release candidate, but the message from Synaptics didn't say so explicitly - I will confirm.

Download it here: https://drive.google.com/file/d/1HtCDsnOxc29ZFm0qb8Bt_m6J5H69WPfQ/view?usp=share_link

Installation instructions:
```
$ sudo cp /lib/firmware/brcm/BCM4345C5.hcd BCM4345C5.hcd.backup
$ sudo cp BCM4345C5_003.006.006.1052.1108.hcd /lib/firmware/brcm/BCM4345C5.hcd
```
and to revert:
```
$ sudo cp BCM4345C5.hcd.backup /lib/firmware/brcm/BCM4345C5.hcd
```

I've done some basic testing - enough to confirm that I can pair simple devices, and that the BLE advertising still works on my older Android phone.

**Comment by pelwell** [comment]
Synaptics have confirmed that this is a release candidate. Once I have some confirmation that it fixes the issue we'll get it into an update ASAP (holiday permitting).

**Comment by cspensky** [comment]
I've been testing this a bit internally, and it seems to be a partial fix.  

FIXED: I can now connect my Pixel 7 and Pixel 6 pretty reliably to my Pi CM4s :raised_hands: 

However, I am still unable to negotiate the MTU with this firmware.  
Specifically, the `gatt.requestMtu(512);` command in Java/Android.

Previously, removing the MTU negotation was my dirty fix to this overarching issue, but the connection was still very unstable.  This fix seems to clean up the connection, but not being able to negotiate the MTU means that the user experience is very sub optimal.  Maybe the bug exists in 2 places? 

Has anyone else been experiencing the same thing?

**Comment by pelwell** [comment]
Closing because the reported problem has been fixed.

**Comment by cspensky** [comment]
FYI, we still have some pretty serious issues with these phones and this firmware.  :-( 
The probably of a phone connecting seems to be somewhere around 70% and can take up to minutes before it finally works.
